version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studentdb
    networks:
      - spring-postgres-network
    ports:
      - "5432:5432"

networks:
  spring-postgres-network:
    driver: bridge
